### ISSUE TITLE
Structural/non-structural labels in the dataset

### ISSUE THREAD

**Issue by ashenvi10** [g-walley/cegpy#14]
Currently the code assumes all NaNs and empty cells to be structurally missing.

However, there might be actual sampling missing values. 
Users could be given the option to specify the labels used for structural/sampling missing values so they can be treated differently.

To begin with, sampling missingness may be assumed to be missing at random and we can do a complete-case analysis (i.e remove the rows with sampling missing values), or we could include them within the event tree under the edge label "missing".

**Comment by g-walley** [comment]
### Missing data

There are four different ways to deal with "missing" data.

1. **Structurally missing values**: Where a variable's recording is missing because it didn't make sense to record it. E.g. patient died.
2. **Missing values**: Where there is no reason for the data to be missing other than the data was not collected.
3. **Structural zero**: Where the value of a variable is never possible given previous events.
4. **Sampling zero**: Where an event could happen but it has never actually been recorded in the dataset.

@ashenvi10 Would you say this is correct? Please modify these definitions if not. 

We need to determine how the user will tell the package which is which.
